name: quizonai_backend

dependencies:
  - python=3.12.7
  - pip=24.2
  - psycopg2=2.9.9
  - pip:
      - django==5.1.3
      - djangorestframework==3.15.2
      - djangorestframework-simplejwt==5.3.1
      - drf-yasg==1.21.8
      - flake8==7.1.1
      - gunicorn==23.0.0
      - pillow==11.0.0
      - django-cors-headers==4.6.0
